[package]
name = "ramp"
description = "A high-performance multiple-precision arithmetic library"
version = "0.3.0"
authors = ["James Miller <james@aatch.net>"]
build = "build.rs"
license = "Apache-2.0"
readme = "README.md"
keywords = ["bignum","math","number"]

repository = "https://github.com/Aatch/ramp"
documentation = "https://aatch.github.io/ramp/ramp/"

[lib]
name = "ramp"
path = "src/lib.rs"

[features]
unstable = [] # To keep travis-cargo happy
asm = []

full-quickcheck = []

[dependencies]
rand = "0.3"
hamming = "0.1"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
rust-gmp = "0.2"
quickcheck = "0.2"
quickcheck_macros = "0.2"
